<a href="https://colab.research.google.com/github/ussalbt/datascience/blob/main/01_03_2022_Numpy_Exercise_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Çalışma

### NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
# sifirdan array olusturma (np.zeros)

In [7]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros(10, dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# birlerden array olusturma (np.ones)

In [10]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.ones(10, dtype = float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# belirlenen değerler ile doldurma (np.full)

In [12]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
# code here (arange)

np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
# code here (linspace)

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
# code here (random.normal)

np.random.normal(10, 4, (3,4))

array([[ 9.34052215, 15.34418342,  4.9328567 ,  5.70763273],
       [11.0068338 , 12.21797335,  6.71550959,  7.37702638],
       [ 7.45133645,  8.01354518,  4.1718955 ,  5.81770528]])

In [ ]:
# code here (random.randint)

np.random.randint(0,10, (3,3))

array([[9, 0, 2],
       [1, 1, 2],
       [5, 7, 8]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [16]:
import numpy as np

In [17]:
# code here(random.randint, hihg=10, size=10)

np.random.randint(10, size = 10)

array([3, 6, 2, 7, 6, 5, 1, 0, 2, 2])

In [18]:
a = np.random.randint(10, size = 10)

In [19]:
# code here (find the dimension of a)

a.ndim

1

In [20]:
# code here (find the shape of a)

a.shape

(10,)

In [21]:
# code here (find the size of a)

a.size

10

In [22]:
# code here (find the dtype of a)

a.dtype

dtype('int64')

In [23]:
b = np.random.randint(10, size = (3,5))

In [24]:
b

array([[7, 4, 1, 3, 6],
       [3, 5, 4, 6, 2],
       [6, 5, 1, 1, 9]])

In [25]:
# code here (find the dimension of b)

b.ndim

2

In [26]:
# code here (find the shape of b)

b.shape

(3, 5)

In [27]:
# code here (find the size of b)

b.size

15

In [28]:
# code here (find the dtype of b)

b.dtype

dtype('int64')

# Yeniden Şekillendirme (Reshaping)

In [29]:
import numpy as np

In [30]:
# code here (find the dtype of b)

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# code here (reshape (3,3) your coding above)

np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a = np.arange(1,10)

In [33]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# code here (find the dimension of a)

a.ndim

1

In [35]:
# code here (reshape a as (1,9) and assign to b)

b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
# code here (find the dimension of b)

b.ndim

2

# Array Birlestirme (Concatenation)

In [37]:
import numpy as np

In [38]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [39]:
# code here (concatenate x and y)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [40]:
z = np.array([7,8,9])

In [41]:
# code here (concatenate x, y and z)

np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# code here (concatenate z, y and x)

np.concatenate([z, x, y])

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

In [ ]:
#iki boyut

In [43]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [44]:
# code here (concatenate a and a)

np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# code here (concatenate a and a)

np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [ ]:
import numpy as np

In [48]:
x = np.array([1,2,3,99,99,3,2,1])

In [49]:
# code here (split x from 3 and 5)

np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [50]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)

a,b,c = np.split(x, [3,5])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([99, 99])

In [53]:
c

array([3, 2, 1])

In [ ]:
#iki boyutlu ayırma

In [54]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
# code here (split m)

np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
ust, alt = np.vsplit(m, [2])

In [60]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
# code here (split m)

np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
sag, sol = np.hsplit(m, [2])

In [67]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [68]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [ ]:
import numpy as np

In [69]:
v = np.array([2,1,4,3,5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [73]:
# code here (sort v)

np.sort(v)

array([1, 2, 3, 4, 5])

In [74]:
v

array([2, 1, 4, 3, 5])

In [75]:
# code here (sort v)

v.sort()

In [76]:
v

array([1, 2, 3, 4, 5])

In [ ]:
#iki boyutlu array siralama

In [77]:
m = np.random.normal(20,5, (3,3))

In [78]:
m

array([[22.06139743, 21.34010015, 22.60399762],
       [18.02204646, 15.24149713, 19.94863655],
       [21.95227759, 23.02421504, 23.99823796]])

In [79]:
# code here (sort m)

np.sort(m, axis = 1)

array([[21.34010015, 22.06139743, 22.60399762],
       [15.24149713, 18.02204646, 19.94863655],
       [21.95227759, 23.02421504, 23.99823796]])

In [80]:
# code here (sort m)

np.sort(m, axis = 0)

array([[18.02204646, 15.24149713, 19.94863655],
       [21.95227759, 21.34010015, 22.60399762],
       [22.06139743, 23.02421504, 23.99823796]])

# Index ile Elemanlara Erişmek

In [81]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([9, 2, 7, 6, 9, 9, 7, 4, 2, 5])

In [82]:
# code here

a[0]

9

In [83]:
# code here

a[-1]

5

In [84]:
a[2], a[5], a[9] = [4, 0, 100]

In [85]:
a

array([  9,   2,   4,   6,   9,   0,   7,   4,   2, 100])

In [86]:
# code here

a[2]

4

In [87]:
# code here

a[5]

0

In [88]:
# code here

a[9]

100

In [89]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 3, 8, 6, 1],
       [9, 5, 3, 1, 4],
       [9, 1, 7, 7, 3]])

In [90]:
# code here

m[0,0]

7

In [91]:
# code here

m[1,1]

5

In [95]:
# code here

m[2, 3]

7

In [96]:
# code here (look at the below array)

m[1, 4] = 99

In [97]:
m

array([[ 7,  3,  8,  6,  1],
       [ 9,  5,  3,  1, 99],
       [ 9,  1,  7,  7,  3]])

In [100]:
# code here (look at the below array)

m[1,4] = 2.2

In [99]:
m

array([[7, 3, 8, 6, 1],
       [9, 5, 3, 1, 2],
       [9, 1, 7, 7, 3]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [101]:
import numpy as np

In [102]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [103]:
# code here (look at the below array)

a[0:3]

array([20, 21, 22])

In [104]:
# code here (look at the below array)

a[:3]

array([20, 21, 22])

In [105]:
# code here (look at the below array)

a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [106]:
# code here (look at the below array)

a[1::2]

array([21, 23, 25, 27, 29])

In [107]:
# code here (look at the below array)

a[0::2]

array([20, 22, 24, 26, 28])

In [108]:
# code here (look at the below array)

a[2::2]

array([22, 24, 26, 28])

In [109]:
# code here (look at the below array)

a[0::3]

array([20, 23, 26, 29])

In [ ]:
#iki boyutlu slice islemleri

In [110]:
m = np.random.randint(10, size = (5,5))

In [111]:
m

array([[5, 2, 5, 3, 9],
       [0, 8, 6, 2, 8],
       [5, 0, 8, 1, 9],
       [3, 8, 4, 4, 7],
       [4, 7, 1, 0, 7]])

In [116]:
# code here (look at the below array)

m[:,0]

array([5, 0, 5, 3, 4])

In [117]:
# code here (look at the below array)

m[:,1]

array([2, 8, 0, 8, 7])

In [118]:
# code here (look at the below array)

m[:,4]

array([9, 8, 9, 7, 7])

In [119]:
m

array([[5, 2, 5, 3, 9],
       [0, 8, 6, 2, 8],
       [5, 0, 8, 1, 9],
       [3, 8, 4, 4, 7],
       [4, 7, 1, 0, 7]])

In [120]:
# code here (look at the below array)

m[0,:]

array([5, 2, 5, 3, 9])

In [121]:
# code here (look at the below array)

m[0]

array([5, 2, 5, 3, 9])

In [122]:
# code here (look at the below array)

m[1,:]

array([0, 8, 6, 2, 8])

In [123]:
# code here (look at the below array)

m[0:2, 0:3]

array([[5, 2, 5],
       [0, 8, 6]])

In [124]:
# code here (look at the below array)

m[:,0:2]

array([[5, 2],
       [0, 8],
       [5, 0],
       [3, 8],
       [4, 7]])

In [125]:
m

array([[5, 2, 5, 3, 9],
       [0, 8, 6, 2, 8],
       [5, 0, 8, 1, 9],
       [3, 8, 4, 4, 7],
       [4, 7, 1, 0, 7]])

In [126]:
# code here (look at the below array)

m[1:3, 0:2]

array([[0, 8],
       [5, 0]])

# Alt Küme Üzerinde İşlem Yapmak

In [127]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[5, 7, 5, 4, 0],
       [5, 8, 7, 9, 1],
       [3, 5, 8, 4, 5],
       [8, 0, 6, 8, 1],
       [1, 5, 2, 4, 7]])

In [128]:
# code here (look at the below array)

alt_a = a[0:3, 0:2]
alt_a

array([[5, 7],
       [5, 8],
       [3, 5]])

In [129]:
# code here (look at the below array)

alt_a[0,0] = 99999
alt_a[1,1] = 888

In [130]:
alt_a

array([[99999,     7],
       [    5,   888],
       [    3,     5]])

In [131]:
a

array([[99999,     7,     5,     4,     0],
       [    5,   888,     7,     9,     1],
       [    3,     5,     8,     4,     5],
       [    8,     0,     6,     8,     1],
       [    1,     5,     2,     4,     7]])

In [132]:
m = np.random.randint(10, size = (5, 5))
m

array([[3, 2, 4, 9, 5],
       [5, 3, 3, 4, 7],
       [0, 5, 6, 5, 3],
       [0, 3, 5, 6, 6],
       [2, 8, 7, 6, 1]])

In [133]:
# code here (look at the below array)

alt_b = m[0:3, 0:2].copy()
alt_b

array([[3, 2],
       [5, 3],
       [0, 5]])

In [134]:
# code here (look at the below array)

alt_b[0,0] = 9999

In [135]:
alt_b

array([[9999,    2],
       [   5,    3],
       [   0,    5]])

In [136]:
m

array([[3, 2, 4, 9, 5],
       [5, 3, 3, 4, 7],
       [0, 5, 6, 5, 3],
       [0, 3, 5, 6, 6],
       [2, 8, 7, 6, 1]])

# Fancy Index ile Elemanlara Erişmek

In [137]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [138]:
# code here

v[1]

3

In [139]:
# code here

v[3]

9

In [140]:
# code here

v[5]

15

In [141]:
# code here

[v[1], v[3], v[5]]

[3, 9, 15]

In [142]:
al_getir = [1,3,5]

In [143]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [144]:
# code here

v[al_getir]

array([ 3,  9, 15])

In [145]:
#iki boyutta fancy

In [146]:
m = np.arange(9).reshape((3,3))

In [147]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [149]:
m[satir, sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [150]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
m[0, [1,2]]

array([1, 2])

In [ ]:
#slice ile fancy

In [152]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [153]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [154]:
v < 3

array([ True,  True, False, False, False])

In [155]:
# code here

v[v < 3]

array([1, 2])

In [156]:
# code here

v[v > 3]

array([4, 5])

In [157]:
# code here

v[v >= 3]

array([3, 4, 5])

In [158]:
# code here

v[v <= 3]

array([1, 2, 3])

In [159]:
# code here

v[v == 3]

array([3])

In [160]:
# code here

v[v != 3]

array([1, 2, 4, 5])

In [161]:
v

array([1, 2, 3, 4, 5])

In [162]:
# code here

v * 2

array([ 2,  4,  6,  8, 10])

In [163]:
# code here

v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [164]:
# code here

v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [165]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [166]:
v - 1

array([0, 1, 2, 3, 4])

In [167]:
v * 5

array([ 5, 10, 15, 20, 25])

In [168]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [169]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [ ]:
#ufunc

In [170]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [171]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [172]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [173]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [174]:
v**2

array([ 1,  4,  9, 16, 25])

In [175]:
v**3

array([  1,   8,  27,  64, 125])

In [176]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [177]:
v % 2

array([1, 0, 1, 0, 1])

In [178]:
np.mod(v, 2)

array([1, 0, 1, 0, 1])

In [179]:
np.absolute(np.array([-3]))

array([3])

In [180]:
np.sin(360)

0.9589157234143065

In [181]:
np.cos(180)

-0.5984600690578581

In [182]:
v = np.array([1,2,3])

In [183]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [184]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [185]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [186]:
?np

In [187]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [188]:
v

array([1, 2, 3])

In [189]:
np.mean(v)

2.0

In [190]:
v.sum()

6

In [191]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [192]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [193]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [194]:
a

array([[5, 1],
       [1, 3]])

In [195]:
b

array([12, 10])

In [196]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])