<a href="https://colab.research.google.com/github/ussalbt/datascience/blob/main/DAwPy_S4_(Pandas_DataFrames%2C_Selection_and_Indexing)_wallace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
import numpy as np
import pandas as pd

 ## Creating a DataFrame using the ``list``s of data and columns

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

In [ ]:
data = [1, 3, 5, 7, 9, 18]
data

[1, 3, 5, 7, 9, 18]

In [ ]:
pd.DataFrame(data = data)

0
0   1
1   3
2   5
3   7
4   9
5  18

In [ ]:
pd.Series(data = data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [ ]:
pd.DataFrame(data = data, columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

 ## Creating a DataFrame using a ``NumPy Arrays``

In [ ]:
m = np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
df=pd.DataFrame(data=m, columns=['var1','var2','var3','var4'])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df.head(1)

var1  var2  var3  var4
0     1     3     5     7

In [ ]:
df.tail(1)

var1  var2  var3  var4
2    17    19    21    23

In [ ]:
df.sample(2)

var1  var2  var3  var4
1     9    11    13    15
0     1     3     5     7

In [ ]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [ ]:
for i in df.columns:
    print(df[i].sum())

27
33
39
45


In [ ]:
df.columns=["new1", "new2", "new3", "new4"]
df

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df.index=["a", "b", "c"]
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
df.rename(columns = {"new1": "a", "new2": "b"})

a   b  new3  new4
a   1   3     5     7
b   9  11    13    15
c  17  19    21    23

In [ ]:
df.rename(index = {"a": 1, "b": 2})

new1  new2  new3  new4
1     1     3     5     7
2     9    11    13    15
c    17    19    21    23

In [ ]:
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
df.shape

(3, 4)

In [ ]:
df.shape[1]

4

In [ ]:
df.ndim

2

In [ ]:
df.size

12

In [ ]:
len(df)

3

In [ ]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df.values)

numpy.ndarray

 ## Creating a DataFrame using a ``dict``

In [ ]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [ ]:
s1

array([9, 5, 6, 7])

In [ ]:
s2

array([5, 8, 6, 8])

In [ ]:
s3

array([10,  5, 14, 11])

In [ ]:
my_dict = {"var1":s1, "var2":s2, "var3":s3}
my_dict

{'var1': array([9, 5, 6, 7]),
 'var2': array([5, 8, 6, 8]),
 'var3': array([10,  5, 14, 11])}

In [ ]:
df1 = pd.DataFrame(my_dict)
df1

var1  var2  var3
0     9     5    10
1     5     8     5
2     6     6    14
3     7     8    11

In [ ]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
[i for i in df1.index]

[0, 1, 2, 3]

In [ ]:
"var2" in df1

True

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [ ]:
from numpy.random import randn

In [ ]:
randn(5,4)

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942],
       [-0.13484072,  0.39052784,  0.16690464,  0.18450186],
       [ 0.80770591,  0.07295968,  0.63878701,  0.3296463 ],
       [-0.49710402, -0.7540697 , -0.9434064 ,  0.48475165],
       [-0.11677332,  1.9017548 ,  0.23812696,  1.99665229]])

In [ ]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [ ]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

#### DataFrame Columns are just Series

In [ ]:
type(df3["W"])

pandas.core.series.Series

In [ ]:
df3[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [ ]:
type(df3[["W"]])

pandas.core.frame.DataFrame

In [ ]:
df3.W

A    8.120550
B    1.953354
C   -6.054505
D    0.566086
E    0.572383
Name: W, dtype: float64

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[["W", "Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df3["W":"Y"]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [ ]:
df3["A":"C"]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [ ]:
df3["A":"C"]["W"]

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [ ]:
df3["A":"C"][["W", "Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813

**Creating a new column:**

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["new"] = df3["X"] * df3["Y"]
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [ ]:
df3["new2"] = [1,2,3,4,5]
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [ ]:
df3 = df3[["new", "new2", "W", "X", "Y", "Z"]]
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

## [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 ### Removing Columns

In [ ]:
df3.drop("new2", axis=1)

new         W         X         Y         Z
A  0.570325  2.706850  0.628133  0.907969  0.503826
B  0.270806  0.651118 -0.319318 -0.848077  0.605965
C  0.391387 -2.018168  0.740122  0.528813 -0.589001
D  0.708208  0.188695 -0.758872 -0.933237  0.955057
E  5.156577  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(["new", "new2"], axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(columns = ["new", "new2"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(["new", "new2"], axis=1, inplace=True)

C:\Users\acer\anaconda3\lib\site-packages\pandas\core\frame.py:4315: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

 ### Removing rows

In [ ]:
df3.drop("C", axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(index = ["B"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df4 = df3.drop("C", axis=0)
df4

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selecting Rows

### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [ ]:
m = np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df4.loc[4]

var1    20
var2    36
var3    31
var4    11
Name: 4, dtype: int32

In [ ]:
df4.loc[[4]]

var1  var2  var3  var4
4    20    36    31    11

In [ ]:
df4.loc[2:5]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [ ]:
df4.iloc[2:5]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11

In [ ]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df4.iloc[1:4]

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [ ]:
#df4.loc[1:4] gives an error

In [ ]:
df4.loc["a":"d"]

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [ ]:
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df4.iloc[3, 1]

30

In [ ]:
df4.loc["d", "var2"]

30

In [ ]:
df4.loc["d":"g", "var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int32

In [ ]:
df4.loc["d":"g"]["var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int32

In [ ]:
df4.loc["d":"g"][["var3"]]

var3
d    25
e    31
f     9
g    38

In [ ]:
df4.loc["d":"g", ["var3"]]

var3
d    25
e    31
f     9
g    38

In [ ]:
df4.iloc[2:5,2]

c    12
d    25
e    31
Name: var3, dtype: int32

In [ ]:
df4.iloc[2:5][["var2"]]

var2
c    18
d    30
e    36

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.loc["C"]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [ ]:
df3.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [ ]:
df3.loc[["C"]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [ ]:
df3.iloc[[2]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.loc["C","Z"]

-0.5890005332865824

In [ ]:
df3.loc[["C"],["Z"]]

Z
C -0.589001

In [ ]:
df3.loc[["A", "C"], ["X", "Z"]]

X         Z
A  0.628133  0.503826
C  0.740122 -0.589001

In [ ]:
df3.iloc[0:2,0:3]

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3>2

W      X      Y      Z
A   True  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False   True  False

In [ ]:
df3[df3>2]

W   X         Y   Z
A  2.70685 NaN       NaN NaN
B      NaN NaN       NaN NaN
C      NaN NaN       NaN NaN
D      NaN NaN       NaN NaN
E      NaN NaN  2.605967 NaN

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[df3["Z"]>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[df3["Z"]>0.5]["X"]

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [ ]:
df3[df3["Z"]>0.5][["X"]]

X
A  0.628133
B -0.319318
D -0.758872
E  1.978757

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [ ]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[(df3['W']>0) & (df3['Y']<1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df3[(df3['W']>0) & (df3['Y']<1)] = 0

In [ ]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.loc[(df3.X>0), ["X", "Y"]]

X         Y
A  0.628133  0.907969
C  0.740122  0.528813
E  1.978757  2.605967

In [ ]:
df3.loc[((df3.W>1) | (df3.Y<1)), ['X','Z']]

X         Z
A  0.628133  0.503826
B -0.319318  0.605965
C  0.740122 -0.589001
D -0.758872  0.955057

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.reset_index(drop = True)

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.set_index("Z")

W         X         Y
Z                                      
 0.503826  2.706850  0.628133  0.907969
 0.605965  0.651118 -0.319318 -0.848077
-0.589001 -2.018168  0.740122  0.528813
 0.955057  0.188695 -0.758872 -0.933237
 0.683509  0.190794  1.978757  2.605967

In [ ]:
df3.reset_index(drop=True, inplace=True)
df3

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

### Let's learn new functions/attributes/methods on "iris dataset" 

# End of the Session