<a href="https://colab.research.google.com/github/ussalbt/datascience/blob/main/DAwPy_S2_(Numpy_Indexing_Selection_Operations)_20_01_ki%C5%9Fisel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[8]

8

In [4]:
arr[-1]

10

In [5]:
arr[-3]

8

In [6]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [10]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [11]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [12]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[1]

array([20, 25, 30])

In [14]:
arr_2d[1][1]

25

In [15]:
arr_2d[1,1]

25

In [16]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[2,1]=99#atama yapılmış

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 99, 45]])

In [21]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 99]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [22]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [23]:
v[[3,5,7]]

array([ 9, 15, 21])

In [24]:
v[3,5,7]#[]önemli

IndexError: ignored

In [25]:
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
for i in range(len(arr2d)):
  arr2d[i] = i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [27]:
arr2d[[2,4,6]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

<h3>any_array[[row indices], [column indices]]</h3>

In [28]:
jj=np.arange(1,17).reshape(4,4)

In [29]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
jj[[1,2],[0,3]]

array([ 5, 12])

### Using ***basic index*** and ***fancy index*** together

In [31]:
jj[2,[2,3]]

array([11, 12])

In [32]:
jj[[2,3],1]

array([10, 14])

using basic slicing 


In [33]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[(arr>3)&(arr<8)]

array([4, 5, 6, 7])

In [40]:
arr[arr!=4]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[(arr>3)]

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[:5]=99

In [43]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_slice =arr[5:]
arr_slice

array([ 6,  7,  8,  9, 10])

In [45]:
arr_slice[-2:] = 55
arr_slice

array([ 6,  7,  8, 55, 55])

In [46]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

In [48]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

In [49]:
arr_copy[2:6] = 0
arr_copy

array([99, 99,  0,  0,  0,  0,  7,  8, 55, 55])

In [50]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [51]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
arr* arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
import warnings
warnings.filterwarnings('ignore')

In [56]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [58]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [63]:
np.sin(np.pi/4)

0.7071067811865475

In [64]:
np.tan(np.pi/4)

0.9999999999999999

In [65]:
np.pi

3.141592653589793

In [66]:
np.log(1000)

6.907755278982137

In [67]:
np.log10(100)

2.0

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``np.corrcoef(arr)`` | Returns correlation coefficient of array

In [68]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [69]:
np.mean(v)

2.142857142857143

In [70]:
v.mean()

2.142857142857143

In [71]:
np.median(v)

2.0

In [72]:
v.std()

0.8329931278350429

In [73]:
v.var()

0.6938775510204082

In [74]:
np.random.seed(42)
xarr = np.random.randn(3,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [75]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.