<a href="https://colab.research.google.com/github/ussalbt/datascience/blob/main/Why_Numpy_(Comparing_list_and_array_by_size_and_computation_time).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Why Numpy?

In [ ]:
import numpy as np
import time
import sys

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [ ]:
#a * b # Gives an error

In [ ]:
ab = []                        

for i in range(0, len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [ ]:
a1 = np.array([1,2,3,4])
b1 = np.array([2,3,4,5])

In [ ]:
a1 * b1

array([ 2,  6, 12, 20])

In [ ]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [ ]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
b1

array([[2, 3, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [ ]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [ ]:
# Nested lists without NumPy.

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### Comparing list and array by size

In [ ]:
l = range(1000)
print("size of one item in list :", sys.getsizeof(5))
print("size of all items in list :", sys.getsizeof(5) * len(l))

print("---" * 10)

a = np.arange(1000)
print("size of one item in array :", a.itemsize)
print("size of all items in array :", a.itemsize * a.size)

size of one item in list : 28
size of all items in list : 28000
------------------------------
size of one item in array : 4
size of all items in array : 4000


### Comparing list and array by computation time

In [ ]:
size = 1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

#python list
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start) * 1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start) * 1000)

python list took:  315.6707286834717
numpy took:  34.42096710205078
